### ISSUE TITLE
VS Code Format On Save

### ISSUE THREAD

**Issue by aseerkt** [vikasg603/razorpay-typescript#2]
I use prettier in vs code.
I am curious whether you are using eslint formatter or prettier for this project.
So I am having trouble formatting files on save causing unnecessary git diffs. 
Can you provide your prettier config or commit the `.prettierrc` file to your repo?.
@vikasg603

**Comment by vikasg603** [comment]
Hey, @aseerkt I used the ESLint for the formating rather than prettier.
the ESLint config is already in the repo.
